### ISSUE TITLE
Disco doesn't update/delete records when k8s resources are updated/removed

### ISSUE THREAD

**Issue by kayrus** [sapcc/kubernetes-operators#44] opened 2022-06-15 07:46 UTC
If a k8s resource with a disco label is removed or updated, the DNS record is kept untouched.

**Comment by auhlig** [comment] 2022-06-15 08:28
That's the expected behavior as described in the readme

**Comment by auhlig** [comment] 2022-06-15 11:09
I closed the issue since I don't see one here.
If the DISCO created the recordset, updates and deletions are done during reconciliation on change of the k8s resource and periodically.
As stated in the readme, there are limitations to the DISCO such as not managing DNS zones as they are done manually in our case, and not all records are deleted if the creator is in question e.g. records created by the disco are cleaned up, records created manually then taken over by disco (ingress/svc/.. created later) are not deleted as they are identified via record description, etc.
Though it would be technically possible to implement these, it's currently out of scope.

**Closed by auhlig** 2022-06-15 11:09 UTC
